name = "memory-note"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
    { binding = "MEMORY_NOTE", id = "ff54fc5eae3a4c228ed6da602023bdba", preview_id = "" }
]
compatibility_date = "2021-09-26"
